### PR TITLE
Adds notification configurations and exposes additional client application functionality.

### PR DESCRIPTION
**Pull request by JPHBrivo**
- BaseGeofenceStore.cs: Add keys for configurable notifications for each 
  event. This allows us to subscribe to entry/exit/stay events
  and independently also get notifications for each event or not as we
  choose.
- GeofenceCircularRegion.cs: GeofenceCircularRegion uses the new
  entry/exit/stay notification flags, defaulting to the existing
  behavior where all are on if notifications are on.
- IGeofence.cs: Add interface implementation of a method that checks
  if location is enabled, so that we can better handle location
  requests in our app if we do not want this function delegated to
  this plugin.
- IGeofenceListener.cs: Add OnAppStarted interface implementation to
  handle app startup state in the client app.
- GeofenceImplementation.cs: Adds location service checks and
  delegates location and permission failures to the client app by
  raising them in a message to the OnError event.
- GeofenceLocationListener.cs: Add robustness to the location updated
  method for usage with the broadcast receiver in an Android
  background service.
- GeofenceStore.cs: Add support for the new entry, exit, and stay
  notification flags for Android.
- GeofenceTransitionsIntentService.cs: Add support to customize the
  large icon and color used in the notification for Android, and
  implement the new entry/exit/stay notification parameters.
- GeofenceImplementation.cs: Force using the UI thread where necessary
  for iOS, and adds parameters that enable delegating location and
  notification prompts to the client app if desired.
- GeofenceStore.cs: Adds support for the new entry/exit/stay
  notification parameters for iOS.
- CrossGeofence.cs: Adds the request notification and location
  permission flags, and the large icon and color for Android
  notifications.

### CODE REVIEW

**Comment by rdelrosario** [comment]
Great stuff! Thanks for collaborating. Will be testing this ASAP. Should readme be updated?

**Comment by JPHBrivo** [comment]
Sure, I can take a crack at that if you like.

**Comment by rdelrosario** [comment]
Amazing work guys! Great collaboration

**Comment by rdelrosario** [comment]
Just released the NuGet package with your changes. Let me know if everything seems ok when you update. Thanks for this great work!

**Comment by JPHBrivo** [comment]
Great - thanks! Will let you know.

**Comment by JPHBrivo** [comment]
We are seeing an issue with testing - the CrossGeofence Android static
properties don't seem to be accessible in our Android project (e.g.
sounduri, color, fastestlocationupdatesinterval, etc.) Might there have
been an issue in the nuget package generation process?

**Comment by rdelrosario** [comment]
Yes, updated the package again. Try again with the newest version and let me know

**Comment by JPHBrivo** [comment]
Looks good. Thanks!

On Fri, Jan 22, 2016 at 4:49 PM, Rendy Del Rosario <notifications@github.com

**Pull request merged**
